project:
  type: manuscript
  output-dir: generated

manuscript:
  article: paper.qmd
  code-links:
    - text: Source Github Repository
      href: https://github.com/CUBoulder-DS/CSCI-5423-Final
      icon: github
  notebooks:
    - notebook: ../Notebooks/EDA_Comparison.ipynb
    - notebook: ../Notebooks/EDA_Werewolf-Arena.ipynb
    - notebook: ../Notebooks/EDA_Werewolf-Among-Us.ipynb

format:
  html:
    theme: minty
    toc: true
    toc-expand: 4
    plotly-connected: true
    search: true
    smooth-scroll: true
    citations-hover: true
    image: Images/logo.png
    # comments: # Enable live user commenting
    #   hypothesis: true
  pdf:
    link-citations: true
    toc: true
    keep-tex: false
    geometry:
      - margin=0.5in
    # equal-margins: false
    # latex-output-dir: "../" # Make PDF NOT be in generated folder
    latex-clean: true # delete latex files after rendering
    fig-pos: H # Make figures render at the location in the doc they were specified!!!
    documentclass: scrreprt # The document format
  # docx: default

quarto-required: ">= 1.4.0"

brand:
  logo:
    medium: Images/logo.png

# bibliography: references.bib
# Force all references in .bib file to appear in References
nocite: |
  @*

execute:
  freeze: auto

## PDF creation settings
latex-clean: true # delete latex files after rendering
latex-auto-mk: true
latex-auto-install: true
